// This file is auto-generated by: supabase gen types typescript --local
// After configuring Supabase, run: npx supabase gen types typescript --local > types/database.ts
// The types below are manually maintained until then.

// Generic fallback type for manual maintenance
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any;

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// ── Manually maintained row types for type safety in application code ──────
export type PatientStatus = "lead" | "new" | "active" | "inactive" | "archived";
export type AppointmentStatus = "pending" | "confirmed" | "in_progress" | "completed" | "cancelled" | "no_show";
export type AppointmentType = "online" | "presencial" | "hybrid";
export type PaymentStatus = "pending" | "paid" | "refunded" | "exempt" | "free";
export type PaymentMethod = "stripe" | "pix" | "manual" | "exempt";
export type MedicalRecordType = "note" | "hypothesis" | "goal" | "evolution" | "attachment" | "risk_assessment";

export interface TherapistRow {
  id: string;
  user_id: string | null;
  name: string;
  crp: string;
  bio: string | null;
  photo_url: string | null;
  slug: string;
  specialties: string[];
  session_price: number;
  session_duration: number;
  timezone: string;
  ai_model: string | null;
  openrouter_key_hash: string | null;
  telegram_bot_token: string | null;
  telegram_chat_id: number | null;
  telegram_bot_username: string | null;
  stripe_account_id: string | null;
  onboarding_completed: boolean;
  active: boolean;
  created_at: string;
  updated_at: string;
}

export interface PatientRow {
  id: string;
  therapist_id: string;
  user_id: string | null;
  name: string;
  email: string;
  phone: string | null;
  telegram_chat_id: number | null;
  telegram_username: string | null;
  birth_date: string | null;
  cpf: string | null;
  address: Json | null;
  emergency_contact: Json | null;
  private_notes: string | null;
  tags: string[];
  status: PatientStatus;
  mood_score: number | null;
  gdpr_consent: boolean;
  gdpr_consent_at: string | null;
  gdpr_consent_ip: string | null;
  onboarding_source: string | null;
  created_at: string;
  updated_at: string;
}

export interface AppointmentRow {
  id: string;
  therapist_id: string;
  patient_id: string;
  scheduled_at: string;
  duration_minutes: number;
  type: AppointmentType;
  status: AppointmentStatus;
  video_room_id: string | null;
  video_room_url: string | null;
  patient_access_token: string | null;
  payment_status: PaymentStatus;
  stripe_session_id: string | null;
  stripe_payment_id: string | null;
  price_charged: number | null;
  cancellation_reason: string | null;
  cancelled_at: string | null;
  cancelled_by: "therapist" | "patient" | "system" | null;
  reminder_24h_sent: boolean;
  reminder_1h_sent: boolean;
  nps_sent: boolean;
  created_at: string;
  updated_at: string;
}

export interface SessionRow {
  id: string;
  appointment_id: string | null;
  therapist_id: string;
  patient_id: string;
  session_number: number;
  started_at: string | null;
  ended_at: string | null;
  duration_seconds: number | null;
  therapist_notes: string | null;
  ai_summary: string | null;
  ai_insights: string[] | null;
  ai_next_steps: string[] | null;
  ai_risk_flags: string[] | null;
  transcript: string | null;
  mood_before: number | null;
  mood_after: number | null;
  nps_score: number | null;
  is_signed: boolean;
  signed_at: string | null;
  signed_hash: string | null;
  created_at: string;
}

export interface MedicalRecordRow {
  id: string;
  patient_id: string;
  therapist_id: string;
  session_id: string | null;
  type: MedicalRecordType;
  content: string;
  is_private: boolean;
  created_at: string;
  updated_at: string;
}

export interface PaymentRow {
  id: string;
  appointment_id: string | null;
  therapist_id: string;
  patient_id: string;
  amount: number;
  currency: string;
  method: PaymentMethod | null;
  stripe_payment_id: string | null;
  pix_qrcode: string | null;
  status: "pending" | "processing" | "paid" | "failed" | "refunded" | "disputed";
  paid_at: string | null;
  refunded_at: string | null;
  refund_reason: string | null;
  created_at: string;
}
